FROM totofunku/bigdata-cours:latest

RUN apt-get update
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev \
    libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev libffi-dev

RUN wget https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz
RUN tar -xf Python-3.9.7.tgz
WORKDIR /root/Python-3.9.7
RUN ./configure --enable-optimizations
RUN make -j$(nproc)
RUN make install
WORKDIR /root/
RUN rm -rf Python-3.9.7 Python-3.9.7.tgz

COPY requirements.txt .
RUN python3.9 -m pip install --upgrade pip
RUN python3.9 -m pip install -r requirements.txt

COPY kafka_connector.py .
COPY KafkaSparkStream-1.0.jar .
COPY get_coins_history.py .