FROM confluentinc/cp-kafka:latest

COPY requirements.txt .

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt

COPY launch /etc/confluent/docker/launch

WORKDIR /home/appuser
COPY app.py .